### ISSUE TITLE
Only first three statements pulled

### ISSUE THREAD

**Issue by philip-sparks** [benradford/Politifact-Scraper#1]
Hi Ben,
After attempting to use your scraper, only the first three statements get repeatedly pulled into the dataframe. I modified the code to get the htmlparse statements to work. Has this attempt broken anything else down the pipeline?
Thanks,

[politifact-scraper.txt](https://github.com/benradford/Politifact-Scraper/files/2527636/politifact-scraper.txt)

**Comment by benradford** [comment]
Thank you, @philip-sparks! This code works on my end. Would you mind submitting a pull request to fix the .R file?

**Comment by philip-sparks** [comment]
Hey Ben, I couldn't get authentication to allow me to send a pull request on your repository, so I fork/cloned it onto my profile.
Here's the link: https://github.com/philip-sparks/Politifact-Scraper/blob/master/politifact-scraper.R
This files creates 5,376 entries in all.statements.df and loops through the first seven statements repeatedly.

**Comment by philip-sparks** [comment]
Just to clarify, running your script as is returns "Error: failed to load external entity "http://www.politifact.com/truth-o-meter/statements"" after line 6. I've tried this in multiple OS environments using R 3.4.4 within RStudio.

**Comment by philip-sparks** [comment]
Very old. Thanks!
